Adds Round 3 Synthesis
HHS/TANF-app pull request #99
Opened 2020-12-07 21:25 UTC by reitermb

### This pull request changes...

Adds Round 3 Synthesis

2020-12-08 17:24 UTC, alexsoble commented
Dropping in this preview link real quick for ease of review: https://github.com/reitermb/TANF-app/blob/main/docs/User-Research/2020%2C%20Fall%20-%20Understanding%20STT%20Roles%2C%20Source%20of%20Truth%2C%20and%20Metadata.md

2020-12-14 19:26 UTC, lfrohlich requested changes
Noted areas for minor edits

2020-12-14 19:26 UTC, lfrohlich commented on docs/User-Research/2020, Fall - Understanding STT Roles, Source of Truth, and Metadata.md
> +- Preference toward participants who have no been interviewed in past research
who have noT been

2020-12-14 19:26 UTC, lfrohlich commented on docs/User-Research/2020, Fall - Understanding STT Roles, Source of Truth, and Metadata.md
> +- Include notifications to alert a user of an incomplete report if the upload sections at different times.
...if theY upload sections...

2020-12-14 19:26 UTC, lfrohlich commented on docs/User-Research/2020, Fall - Understanding STT Roles, Source of Truth, and Metadata.md
> +Some grantees seemed to understood encryption as being something roughly equivalent to 'non human-readable'. Others did connect our question about encryption with the TANF header data point regarding
some grantees seemed to underSTAND...

2020-12-14 19:43 UTC, reitermb commented
Thanks @lfrohlich—Should be updated now!

2020-12-14 19:58 UTC, lfrohlich approved these changes
Thanks!

2020-12-14 19:58 UTC, merged